package com.example.appbusinessassignment.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COMIC_DATA".
 */
public class comicData {

    private Integer id;
    private String title;
    private String description;
    private Integer pageCount;
    private Double price;
    private String author;
    private String image;
    private String imageExtension;

    public comicData() {
    }

    public comicData(Integer id, String title, String description, Integer pageCount, Double price, String author, String image, String imageExtension) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.pageCount = pageCount;
        this.price = price;
        this.author = author;
        this.image = image;
        this.imageExtension = imageExtension;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getPageCount() {
        return pageCount;
    }

    public void setPageCount(Integer pageCount) {
        this.pageCount = pageCount;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getImageExtension() {
        return imageExtension;
    }

    public void setImageExtension(String imageExtension) {
        this.imageExtension = imageExtension;
    }

}
