package com.example.appbusinessassignment.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.appbusinessassignment.database.comicData;
import com.example.appbusinessassignment.database.minmaxData;

import com.example.appbusinessassignment.database.comicDataDao;
import com.example.appbusinessassignment.database.minmaxDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig comicDataDaoConfig;
    private final DaoConfig minmaxDataDaoConfig;

    private final comicDataDao comicDataDao;
    private final minmaxDataDao minmaxDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        comicDataDaoConfig = daoConfigMap.get(comicDataDao.class).clone();
        comicDataDaoConfig.initIdentityScope(type);

        minmaxDataDaoConfig = daoConfigMap.get(minmaxDataDao.class).clone();
        minmaxDataDaoConfig.initIdentityScope(type);

        comicDataDao = new comicDataDao(comicDataDaoConfig, this);
        minmaxDataDao = new minmaxDataDao(minmaxDataDaoConfig, this);

        registerDao(comicData.class, comicDataDao);
        registerDao(minmaxData.class, minmaxDataDao);
    }
    
    public void clear() {
        comicDataDaoConfig.getIdentityScope().clear();
        minmaxDataDaoConfig.getIdentityScope().clear();
    }

    public comicDataDao getComicDataDao() {
        return comicDataDao;
    }

    public minmaxDataDao getMinmaxDataDao() {
        return minmaxDataDao;
    }

}
